behaviors:
  SoccerTwos:
    trainer_type: poca
    hyperparameters:
      batch_size: 4096
      buffer_size: 20480
      learning_rate: 0.0001
      beta: 0.004
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 12
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 1500
    summary_freq: 3000
    self_play:
      save_steps: 50000
      team_change: 100000
      swap_steps: 1000
      window: 3
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0
